USE [GESTAO-FABRICA-VESTUARIO-LABORAL]
GO
--querys de listagens:
--SELECT * FROM CLIENTE JOIN ZONA ON CLIENTE.COD_POSTAL=ZONA.COD_POSTAL

-- listagem encomendas
/*
SELECT ENCOMENDA.N_ENCOMENDA AS NENCOMENDA, REFERENCIA_PRODUTO, TAMANHO_PRODUTO, COR_PRODUTO, 
QUANTIDADE, ESTADO, CLIENTE.NOME as CLIENTENAME, [PRODUTO-BASE].NOME as PRODUCT_NAME, DATA_ENTREGA_PREV
FROM ( (CONTEUDO_ENCOMENDA JOIN ENCOMENDA ON CONTEUDO_ENCOMENDA.N_ENCOMENDA = ENCOMENDA.N_ENCOMENDA)
JOIN CLIENTE ON CLIENTE.NCLIENTE = ENCOMENDA.CLIENTE ) 
JOIN [PRODUTO-BASE] ON CONTEUDO_ENCOMENDA.REFERENCIA_PRODUTO = [PRODUTO-BASE].REFERENCIA
*/
--listagem de produtos base
SELECT SELECT REFERENCIA, [PRODUTO-BASE].NOME as nomeProduto, INSTRUCOES_PRODUCAO,DATA_ALTERACAO, IVA, 
N_FUNCIONARIO, UTILIZADOR.NOME as userName FROM [PRODUTO-BASE] JOIN UTILIZADOR ON N_GESTOR_PROD=N_FUNCIONARIO

-- listagem de produtos personalizados

SELECT TAMANHO, COR, ID, PRECO, UNIDADES_ARMAZEM, [PRODUTO-PERSONALIZADO].REFERENCIA, [PRODUTO-BASE].NOME as nomeBase,
 DATA_ALTERACAO, INSTRUCOES_PRODUCAO, IVA, PAIS_FABRICO, [PRODUTO-PERSONALIZADO].N_ETIQUETA, NORMAS, PAIS_FABRICO, COMPOSICAO 
 FROM [PRODUTO-PERSONALIZADO] JOIN [PRODUTO-BASE] ON [PRODUTO-PERSONALIZADO].REFERENCIA = [PRODUTO-BASE].REFERENCIA
 JOIN ETIQUETA ON ETIQUETA.N_ETIQUETA = [PRODUTO-PERSONALIZADO].N_ETIQUETA;

--listagem de etiquetas
SELECT * FROM ETIQUETA
--obter uma etiquetas espcifica (para o registo de desenho pers, caso o user crie uma nova etiqueta
SELECT N_ETIQUETA FROM ETIQUETA 
WHERE (NORMAS = 'Mais exemplos de normas' AND PAIS_FABRICO = 'Espanha'AND COMPOSICAO = 'Pano, linha')

--obter de um cliente
SELECT N_ENCOMENDA, DATA_CONFIRMACAO, DATA_ENTREGA, LOCALENTREGA, ESTADO, N_GESTOR_VENDA, UTILIZADOR.NOME as GESTOR_NOME
FROM ENCOMENDA JOIN UTILIZADOR ON N_FUNCIONARIO = N_GESTOR_VENDA
WHERE CLIENTE = '2'

SELECT * FROM [FABRICA-FILIAL] JOIN ZONA ON ([FABRICA-FILIAL].CODPOSTAL1 = ZONA.CODPOSTAL1 AND [FABRICA-FILIAL].CODPOSTAL2 = ZONA.CODPOSTAL2)