--indices

CREATE INDEX zonaIndex
ON ZONA (CODPOSTAL1, CODPOSTAL2);


--DROP INDEX [FABRICA-FILIAL].filiaisIndex

CREATE INDEX fornIndex
ON FORNECEDOR (NIF);

CREATE INDEX utilIndex
ON UTILIZADOR (N_FUNCIONARIO);
