CREATE FUNCTION dbo.getEncomendasMes () RETURNS int
AS
BEGIN
	DECLARE @x INT;
	SELECT @x=COUNT(*) 
	FROM ENCOMENDA
	WHERE ESTADO=1 AND Year(DATA_ENTREGA_PREV) = Year(CURRENT_TIMESTAMP) AND Month(DATA_ENTREGA_PREV) = Month(CURRENT_TIMESTAMP)
	RETURN @x;
END
GO

CREATE FUNCTION dbo.getDinheiroGeradoMes() RETURNS decimal(10,2)
BEGIN
	DECLARE @x decimal(10,2) = 0;
	SELECT @x=SUM(TOTAL-((DESCONTO*TOTAL)/100)) FROM (
	SELECT ENCOMENDA.N_ENCOMENDA, SUM(CONTEUDO_ENCOMENDA.QUANTIDADE * [PRODUTO-PERSONALIZADO].PRECO) AS TOTAL, DESCONTO
	FROM ENCOMENDA JOIN CONTEUDO_ENCOMENDA ON ENCOMENDA.N_ENCOMENDA=ENCOMENDA.N_ENCOMENDA 
	JOIN [PRODUTO-PERSONALIZADO] ON [PRODUTO-PERSONALIZADO].REFERENCIA=CONTEUDO_ENCOMENDA.REFERENCIA_PRODUTO 
	AND [PRODUTO-PERSONALIZADO].TAMANHO=CONTEUDO_ENCOMENDA.TAMANHO_PRODUTO 
	AND [PRODUTO-PERSONALIZADO].ID=CONTEUDO_ENCOMENDA.ID_PRODUTO
	WHERE Year(DATA_ENTREGA) = Year(CURRENT_TIMESTAMP) AND Month(DATA_ENTREGA) = Month(CURRENT_TIMESTAMP)
	GROUP BY ENCOMENDA.N_ENCOMENDA, DESCONTO) TEMP;
	RETURN @x;
END
GO


CREATE FUNCTION dbo.getDinheiroGastoMes() RETURNS decimal(10,2)
BEGIN
	DECLARE @x decimal(10,2);
	SELECT @X=SUM(CONTEUDO_ENCOMENDA.QUANTIDADE*[MATERIAIS-PRODUTO].QUANTIDADE * PRECO)
	FROM ENCOMENDA JOIN CONTEUDO_ENCOMENDA ON ENCOMENDA.N_ENCOMENDA=ENCOMENDA.N_ENCOMENDA 
	JOIN [PRODUTO-PERSONALIZADO] ON [PRODUTO-PERSONALIZADO].REFERENCIA=CONTEUDO_ENCOMENDA.REFERENCIA_PRODUTO 
	AND [PRODUTO-PERSONALIZADO].TAMANHO=CONTEUDO_ENCOMENDA.TAMANHO_PRODUTO 
	AND [PRODUTO-PERSONALIZADO].ID=CONTEUDO_ENCOMENDA.ID_PRODUTO
	JOIN [MATERIAIS-PRODUTO] ON [PRODUTO-PERSONALIZADO].REFERENCIA=[MATERIAIS-PRODUTO].REFERENCIA 
	AND [PRODUTO-PERSONALIZADO].TAMANHO=[MATERIAIS-PRODUTO].TAMANHO 
	AND [PRODUTO-PERSONALIZADO].ID=[MATERIAIS-PRODUTO].ID
	JOIN MATERIAIS_TÊXTEIS ON MATERIAIS_TÊXTEIS.REFERENCIA_FABRICA=[MATERIAIS-PRODUTO].REFERENCIA_FABRICA
	WHERE Year(DATA_ENTREGA) = Year(CURRENT_TIMESTAMP) AND Month(DATA_ENTREGA) = Month(CURRENT_TIMESTAMP);
	RETURN @x;
END
GO

--drop function dbo.getDinheiroGastoMes
--drop function dbo.getDinheiroGeradoMes

CREATE FUNCTION dbo.getLucroGeradoMes() RETURNS decimal(10,2)
BEGIN
	DECLARE @lucro decimal(10,2);
	DECLARE @dinheiroGerado decimal (10,2);
	DECLARE @dinheiroGasto decimal(10,2);
	set @dinheiroGasto = dbo.getDinheiroGastoMes();
	set @dinheiroGerado = dbo.getDinheiroGeradoMes();
	set @lucro = @dinheiroGerado-@dinheiroGasto;
	return @lucro;
END
GO

CREATE FUNCTION dbo.getTipoMaisVendidoMes() RETURNS TABLE
AS
RETURN(
	SELECT top 1 REFERENCIA, NOME, SUM(QUANTIDADE) AS QTDPRODUTO FROM ENCOMENDA
	JOIN CONTEUDO_ENCOMENDA ON ENCOMENDA.N_ENCOMENDA=ENCOMENDA.N_ENCOMENDA 
	JOIN [PRODUTO-BASE] ON [PRODUTO-BASE].REFERENCIA=CONTEUDO_ENCOMENDA.REFERENCIA_PRODUTO 
	WHERE ENCOMENDA.ESTADO=2 AND Year(DATA_ENTREGA) = Year(CURRENT_TIMESTAMP) AND Month(DATA_ENTREGA) = Month(CURRENT_TIMESTAMP)
	GROUP BY REFERENCIA, NOME
	ORDER BY  SUM(QUANTIDADE) DESC
)
GO

CREATE FUNCTION dbo.getTotalProdutosVendidosMes() RETURNS INT
AS
BEGIN
	DECLARE @TOTAL INT;
	SELECT @TOTAL=SUM(QUANTIDADE) FROM ENCOMENDA
	JOIN CONTEUDO_ENCOMENDA ON ENCOMENDA.N_ENCOMENDA=CONTEUDO_ENCOMENDA.N_ENCOMENDA 
	WHERE ENCOMENDA.ESTADO=2 AND Year(DATA_ENTREGA) = Year(CURRENT_TIMESTAMP) AND Month(DATA_ENTREGA) = Month(CURRENT_TIMESTAMP);
	RETURN @TOTAL;
END
GO

