--indices

CREATE INDEX zonaIndex
ON ZONA (CODPOSTAL1, CODPOSTAL2);

CREATE UNIQUE CLUSTERED INDEX filiIndex
ON [FABRICA-FILIAL] (N_FILIAL) WITH FILLFACTOR = 95;

--DROP INDEX [FABRICA-FILIAL].filiaisIndex

CREATE INDEX fornIndex
ON FORNECEDOR (NIF);

CREATE INDEX utilIndex
ON UTILIZADOR (N_FUNCIONARIO);
