USE [GESTAO-FABRICA-VESTUARIO-LABORAL]
GO
--querys de listagens:
--SELECT * FROM CLIENTE JOIN ZONA ON CLIENTE.COD_POSTAL=ZONA.COD_POSTAL

-- listagem encomendas
/*
SELECT ENCOMENDA.N_ENCOMENDA AS NENCOMENDA, REFERENCIA_PRODUTO, TAMANHO_PRODUTO, COR_PRODUTO, 
QUANTIDADE, ESTADO, CLIENTE.NOME as CLIENTENAME, [PRODUTO-BASE].NOME as PRODUCT_NAME, DATA_ENTREGA_PREV
FROM ( (CONTEUDO_ENCOMENDA JOIN ENCOMENDA ON CONTEUDO_ENCOMENDA.N_ENCOMENDA = ENCOMENDA.N_ENCOMENDA)
JOIN CLIENTE ON CLIENTE.NCLIENTE = ENCOMENDA.CLIENTE ) 
JOIN [PRODUTO-BASE] ON CONTEUDO_ENCOMENDA.REFERENCIA_PRODUTO = [PRODUTO-BASE].REFERENCIA
*/
--listagem de desenhos personalizados
--SELECT N_DESENHO, NOME_DESENHO, DATA_ALTERACAO, INTRUÇÕES_PRODUÇÃO, N_GESTOR_PROD, UTILIZADOR.NOME FROM DESENHO JOIN UTILIZADOR ON N_GESTOR_PROD=N_FUNCIONARIO

SELECT * FROM [MATERIAIS-DESENHO]

--querys de inserçao:

