USE [GESTAO-FABRICA-VESTUARIO-LABORAL]
GO
--querys de listagens:
--SELECT * FROM CLIENTE JOIN ZONA ON CLIENTE.COD_POSTAL=ZONA.COD_POSTAL

-- listagem encomendas
/*
SELECT ENCOMENDA.N_ENCOMENDA AS NENCOMENDA, REFERENCIA_PRODUTO, TAMANHO_PRODUTO, COR_PRODUTO, 
QUANTIDADE, ESTADO, CLIENTE.NOME as CLIENTENAME, [PRODUTO-BASE].NOME as PRODUCT_NAME, DATA_ENTREGA_PREV
FROM ( (CONTEUDO_ENCOMENDA JOIN ENCOMENDA ON CONTEUDO_ENCOMENDA.N_ENCOMENDA = ENCOMENDA.N_ENCOMENDA)
JOIN CLIENTE ON CLIENTE.NCLIENTE = ENCOMENDA.CLIENTE ) 
JOIN [PRODUTO-BASE] ON CONTEUDO_ENCOMENDA.REFERENCIA_PRODUTO = [PRODUTO-BASE].REFERENCIA
*/
--listagem de desenhos base
--SELECT N_DESENHO, NOME_DESENHO, DATA_ALTERACAO, INSTRUCOES_PRODUCAO, N_GESTOR_PROD, UTILIZADOR.NOME FROM DESENHO JOIN UTILIZADOR ON N_GESTOR_PROD=N_FUNCIONARIO
-- listagem de desenhos personalizados
/*
SELECT N_MODELO, MODELO.N_DESENHO as Ndesenho, ETIQUETA.N_ETIQUETA as Netiqueta, NORMAS, PAIS_FABRICO, COMPOSICAO,
NOME_DESENHO, DATA_ALTERACAO, INSTRUCOES_PRODUCAO, N_GESTOR_PROD, NOME FROM MODELO JOIN ETIQUETA ON ETIQUETA.N_ETIQUETA = MODELO.N_ETIQUETA
JOIN DESENHO ON DESENHO.N_DESENHO = MODELO.N_DESENHO JOIN UTILIZADOR  ON N_GESTOR_PROD = N_FUNCIONARIO
*/
--listagem de etiquetas
SELECT * FROM ETIQUETA
--obter uma etiquetas espcifica (para o registo de desenho pers, caso o user crie uma nova etiqueta
SELECT N_ETIQUETA FROM ETIQUETA 
WHERE (NORMAS = 'Mais exemplos de normas' AND PAIS_FABRICO = 'Espanha'AND COMPOSICAO = 'Pano, linha')

--obter de um cliente
SELECT N_ENCOMENDA, DATA_CONFIRMACAO, DATA_ENTREGA, LOCALENTREGA, ESTADO, N_GESTOR_VENDA, UTILIZADOR.NOME
FROM ENCOMENDA JOIN UTILIZADOR ON N_FUNCIONARIO = N_GESTOR_VENDA
WHERE CLIENTE = '1'
