USE [GESTAO-FABRICA-VESTUARIO-LABORAL]
GO

CREATE FUNCTION dbo.getEncomendasMes () RETURNS int
AS
BEGIN
	DECLARE @x INT;
	SELECT @x=COUNT(*) 
	FROM ENCOMENDA
	WHERE Year(DATA_ENTREGA_PREV) = Year(CURRENT_TIMESTAMP) AND Month(DATA_ENTREGA_PREV) = Month(CURRENT_TIMESTAMP)
	RETURN @x;
END

CREATE FUNCTION dbo.getLucrosMes() RETURNS decimal(10,2)
BEGIN
	DECLARE @x decimal(10,2);
	SELECT @x=SUM(QUANTIDADE * PRECO)
	FROM ENCOMENDA JOIN CONTEUDO_ENCOMENDA ON ENCOMENDA.N_ENCOMENDA=ENCOMENDA.N_ENCOMENDA 
	JOIN [PRODUTO-PERSONALIZADO] ON [PRODUTO-PERSONALIZADO].REFERENCIA=CONTEUDO_ENCOMENDA.REFERENCIA_PRODUTO 
	AND [PRODUTO-PERSONALIZADO].COR=CONTEUDO_ENCOMENDA.COR_PRODUTO 
	AND [PRODUTO-PERSONALIZADO].TAMANHO=CONTEUDO_ENCOMENDA.TAMANHO_PRODUTO 
	AND [PRODUTO-PERSONALIZADO].ID=CONTEUDO_ENCOMENDA.ID_PRODUTO
	WHERE Year(DATA_ENTREGA) = Year(CURRENT_TIMESTAMP) AND Month(DATA_ENTREGA) = Month(CURRENT_TIMESTAMP);
	RETURN @x;
END

CREATE FUNCTION dbo.getProdutoMaisVendidoMes() RETURNS table
AS
RETURN (
SELECT REFERENCIA, MAX(QTDPRODUTO) FROM (
SELECT REFERENCIA,MAX(SUM(QUANTIDADE)) AS QTDPRODUTO FROM ENCOMENDA
JOIN CONTEUDO_ENCOMENDA ON ENCOMENDA.N_ENCOMENDA=ENCOMENDA.N_ENCOMENDA 
JOIN [PRODUTO-BASE] ON [PRODUTO-BASE].REFERENCIA=CONTEUDO_ENCOMENDA.REFERENCIA_PRODUTO 
GROUP BY REFERENCIA) )
GO
print dbo.getLucrosMes();
