USE [GESTAO-FABRICA-VESTUARIO-LABORAL]
GO

CREATE FUNCTION dbo.getEncomendasMes () RETURNS int
AS
BEGIN
	DECLARE @x INT;
	SELECT @x=COUNT(*) 
	FROM ENCOMENDA
	WHERE Year(DATA_ENTREGA_PREV) = Year(CURRENT_TIMESTAMP) AND Month(DATA_ENTREGA_PREV) = Month(CURRENT_TIMESTAMP)
	RETURN @x;
END

CREATE FUNCTION dbo.getDinheiroGeradoMes() RETURNS decimal(10,2)
BEGIN
	DECLARE @x decimal(10,2);
	SELECT @x=SUM(QUANTIDADE * PRECO)
	FROM ENCOMENDA JOIN CONTEUDO_ENCOMENDA ON ENCOMENDA.N_ENCOMENDA=ENCOMENDA.N_ENCOMENDA 
	JOIN [PRODUTO-PERSONALIZADO] ON [PRODUTO-PERSONALIZADO].REFERENCIA=CONTEUDO_ENCOMENDA.REFERENCIA_PRODUTO 
	AND [PRODUTO-PERSONALIZADO].COR=CONTEUDO_ENCOMENDA.COR_PRODUTO 
	AND [PRODUTO-PERSONALIZADO].TAMANHO=CONTEUDO_ENCOMENDA.TAMANHO_PRODUTO 
	AND [PRODUTO-PERSONALIZADO].ID=CONTEUDO_ENCOMENDA.ID_PRODUTO
	WHERE Year(DATA_ENTREGA) = Year(CURRENT_TIMESTAMP) AND Month(DATA_ENTREGA) = Month(CURRENT_TIMESTAMP);
	RETURN @x;
END


CREATE FUNCTION dbo.getDinheiroGastoMes() RETURNS decimal(10,2)
BEGIN
	DECLARE @x decimal(10,2);
	SELECT @X=SUM(CONTEUDO_ENCOMENDA.QUANTIDADE*[MATERIAIS-PRODUTO].QUANTIDADE * PRECO)
	FROM ENCOMENDA JOIN CONTEUDO_ENCOMENDA ON ENCOMENDA.N_ENCOMENDA=ENCOMENDA.N_ENCOMENDA 
	JOIN [PRODUTO-PERSONALIZADO] ON [PRODUTO-PERSONALIZADO].REFERENCIA=CONTEUDO_ENCOMENDA.REFERENCIA_PRODUTO 
	AND [PRODUTO-PERSONALIZADO].COR=CONTEUDO_ENCOMENDA.COR_PRODUTO 
	AND [PRODUTO-PERSONALIZADO].TAMANHO=CONTEUDO_ENCOMENDA.TAMANHO_PRODUTO 
	AND [PRODUTO-PERSONALIZADO].ID=CONTEUDO_ENCOMENDA.ID_PRODUTO
	JOIN [MATERIAIS-PRODUTO] ON [PRODUTO-PERSONALIZADO].REFERENCIA=[MATERIAIS-PRODUTO].REFERENCIA 
	AND [PRODUTO-PERSONALIZADO].COR=[MATERIAIS-PRODUTO].COR
	AND [PRODUTO-PERSONALIZADO].TAMANHO=[MATERIAIS-PRODUTO].TAMANHO 
	AND [PRODUTO-PERSONALIZADO].ID=[MATERIAIS-PRODUTO].ID
	JOIN MATERIAIS_TÊXTEIS ON MATERIAIS_TÊXTEIS.REFERENCIA_FABRICA=[MATERIAIS-PRODUTO].REFERENCIA_FABRICA
	WHERE Year(DATA_ENTREGA) = Year(CURRENT_TIMESTAMP) AND Month(DATA_ENTREGA) = Month(CURRENT_TIMESTAMP);
	RETURN @x;
END


CREATE FUNCTION dbo.getLucroGeradoMes() RETURNS decimal(10,2)
BEGIN
	DECLARE @lucro decimal(10,2);
	DECLARE @dinheiroGerado decimal (10,2);
	DECLARE @dinheiroGasto decimal(10,2);
	set @dinheiroGasto = dbo.getDinheiroGastoMes();
	set @dinheiroGerado = dbo.getDinheiroGeradoMes();
	set @lucro = @dinheiroGerado-@dinheiroGasto;
	return @lucro;
END

CREATE FUNCTION dbo.getProdutoMaisVendidoMes() RETURNS TABLE
AS
RETURN(
	SELECT top 1 REFERENCIA , SUM(QUANTIDADE) AS QTDPRODUTO FROM ENCOMENDA
	JOIN CONTEUDO_ENCOMENDA ON ENCOMENDA.N_ENCOMENDA=ENCOMENDA.N_ENCOMENDA 
	JOIN [PRODUTO-BASE] ON [PRODUTO-BASE].REFERENCIA=CONTEUDO_ENCOMENDA.REFERENCIA_PRODUTO 
	WHERE Year(DATA_ENTREGA) = Year(CURRENT_TIMESTAMP) AND Month(DATA_ENTREGA) = Month(CURRENT_TIMESTAMP)
	GROUP BY REFERENCIA
	ORDER BY  SUM(QUANTIDADE) DESC
)
GO

CREATE FUNCTION dbo.getTotalProdutosVendidosMes() RETURNS INT
AS
BEGIN
	DECLARE @TOTAL INT;
	SELECT @TOTAL=SUM(QUANTIDADE) FROM ENCOMENDA
	JOIN CONTEUDO_ENCOMENDA ON ENCOMENDA.N_ENCOMENDA=ENCOMENDA.N_ENCOMENDA 
	JOIN [PRODUTO-BASE] ON [PRODUTO-BASE].REFERENCIA=CONTEUDO_ENCOMENDA.REFERENCIA_PRODUTO 
	WHERE Year(DATA_ENTREGA) = Year(CURRENT_TIMESTAMP) AND Month(DATA_ENTREGA) = Month(CURRENT_TIMESTAMP);
	RETURN @TOTAL;
END
GO



