USE [GESTAO-FABRICA-VESTUARIO-LABORAL]
GO


CREATE PROC dbo.entregarEncomenda (@NENCOMENDA INT, @OUT VARCHAR(70) OUTPUT)
as 
begin
		DECLARE @QTDPRECISA INT;
		DECLARE @QTDEXISTENTE INT;
		DECLARE @ENTRGAENCOMENDA BIT;
		SET @ENTRGAENCOMENDA=1;
		DECLARE @REFERENCIA INT;
		DECLARE @TAMANHO VARCHAR(5);
		DECLARE @COR VARCHAR(15);
		DECLARE @ID INT;
		DECLARE @ESTADO INT;
		SELECT @ESTADO=ENCOMENDA.ESTADO FROM ENCOMENDA WHERE N_ENCOMENDA=@NENCOMENDA;
		IF(@ESTADO = 2)
			BEGIN
				SET @OUT = 'A encomenda já foi entregue!';
				RETURN
			END		
		ELSE IF (@ESTADO = 3)
			BEGIN
				SET @OUT = 'A encomenda foi cancelada. Não pode ser entregue!';
				RETURN
			END		
		DECLARE cursorProduto CURSOR LOCAL FOR 
				SELECT CONTEUDO_ENCOMENDA.QUANTIDADE, [PRODUTO-PERSONALIZADO].UNIDADES_ARMAZEM, [PRODUTO-PERSONALIZADO].REFERENCIA, [PRODUTO-PERSONALIZADO].TAMANHO, [PRODUTO-PERSONALIZADO].COR, [PRODUTO-PERSONALIZADO].ID FROM CONTEUDO_ENCOMENDA 
				JOIN [PRODUTO-PERSONALIZADO] ON [PRODUTO-PERSONALIZADO].REFERENCIA=CONTEUDO_ENCOMENDA.REFERENCIA_PRODUTO 
				AND [PRODUTO-PERSONALIZADO].COR=CONTEUDO_ENCOMENDA.COR_PRODUTO 
				AND [PRODUTO-PERSONALIZADO].TAMANHO=CONTEUDO_ENCOMENDA.TAMANHO_PRODUTO 
				AND [PRODUTO-PERSONALIZADO].ID=CONTEUDO_ENCOMENDA.ID_PRODUTO
				WHERE CONTEUDO_ENCOMENDA.N_ENCOMENDA=@NENCOMENDA;
				OPEN cursorProduto;
				FETCH cursorProduto INTO @QTDPRECISA, @QTDEXISTENTE, @REFERENCIA, @TAMANHO, @COR, @ID;
				WHILE @@FETCH_STATUS= 0
				BEGIN
					IF @QTDEXISTENTE<@QTDPRECISA
						SET @ENTRGAENCOMENDA=0;
					FETCH cursorProduto INTO @QTDPRECISA, @QTDEXISTENTE, @REFERENCIA, @TAMANHO, @COR, @ID;
				END

				IF @ENTRGAENCOMENDA=0
					BEGIN	
						SET @OUT = 'Não existem produtos suficientes para entregar a encomenda';
					END
				ELSE
					BEGIN
						CLOSE cursorProduto;
						OPEN cursorProduto;
						FETCH cursorProduto INTO @QTDPRECISA, @QTDEXISTENTE, @REFERENCIA, @TAMANHO, @COR, @ID;
						WHILE @@FETCH_STATUS= 0
						BEGIN
							UPDATE [PRODUTO-PERSONALIZADO] 
							SET UNIDADES_ARMAZEM=UNIDADES_ARMAZEM-@QTDPRECISA 
							WHERE [PRODUTO-PERSONALIZADO].REFERENCIA=@REFERENCIA 
							AND [PRODUTO-PERSONALIZADO].TAMANHO=@TAMANHO 
							AND [PRODUTO-PERSONALIZADO].COR=@COR 
							AND [PRODUTO-PERSONALIZADO].ID=@ID;
							FETCH cursorProduto INTO @QTDPRECISA, @QTDEXISTENTE, @REFERENCIA, @TAMANHO, @COR, @ID;
						END
						UPDATE ENCOMENDA SET ESTADO=2, DATA_ENTREGA=CAST(GETDATE() AS DATE) WHERE ENCOMENDA.N_ENCOMENDA=@NENCOMENDA
						SET @OUT = 'Encomenda Entregue';
					END
				CLOSE cursorProduto;		
END
go

USE [GESTAO-FABRICA-VESTUARIO-LABORAL]
GO

CREATE PROC dbo.cancelarEncomenda (@NENCOMENDA INT, @OUT VARCHAR(70) OUTPUT)
as 
	BEGIN
		DECLARE @ESTADO INT;
		SELECT @ESTADO=ENCOMENDA.ESTADO FROM ENCOMENDA WHERE N_ENCOMENDA=@NENCOMENDA;
		IF(@ESTADO = 3)
			BEGIN
				SET @OUT = 'A encomenda já foi cancelada!';
				RETURN
			END		
		ELSE IF (@ESTADO =2)
			BEGIN
				SET @OUT = 'Uma encomenda já entregue não pode ser cancelada!';
				RETURN
			END	
		ELSE 
			BEGIN
				UPDATE ENCOMENDA SET ESTADO=3 WHERE N_ENCOMENDA=@NENCOMENDA;
				SET @OUT = 'A encomenda foi cancelada com sucesso.';
			END		
	END
go

--declare @result varchar(70);
--exec dbo.entregarEncomenda 2, @result output;
--print @result;