USE [GESTAO-FABRICA-VESTUARIO-LABORAL]
GO



 CREATE FUNCTION dbo.getTypeID (@type varchar(50) ) RETURNS INT
AS
	BEGIN
		DECLARE @ID INT
		SELECT @ID = ID FROM [TIPO-UTILIZADOR] 
		WHERE TIPO = @type
		return @ID
	END
GO



SELECT * FROM [FABRICA-FILIAL]