
 CREATE FUNCTION dbo.getTypeID (@type varchar(50) ) RETURNS INT
AS
	BEGIN
		DECLARE @ID INT
		SELECT @ID = ID FROM [TIPO-UTILIZADOR] 
		WHERE TIPO = @type
		return @ID
	END
GO



 CREATE FUNCTION dbo.getUserPass (@nFunc int ) RETURNS VARCHAR(30)
AS
	BEGIN
		DECLARE @pass VARCHAR(30)
		SELECT @pass = PASS FROM UTILIZADOR 
		WHERE N_FUNCIONARIO = @nFunc
		return @pass
	END
GO
