USE [GESTAO-FABRICA-VESTUARIO-LABORAL]
GO



 CREATE FUNCTION dbo.getTypeID (@type varchar(50) ) RETURNS INT
AS
	BEGIN
		DECLARE @ID INT
		SELECT @ID = ID FROM [TIPO-UTILIZADOR] 
		WHERE TIPO = @type
		return @ID
	END
GO



SELECT N_FUNCIONARIO, NOME, EMAIL, TELEFONE, RUA, N_PORTA, 
DISTRITO, LOCALIDADE, SALARIO, N_FABRICA, HORA_ENTRADA, HORA_SAIDA, UTILIZADOR.CODPOSTAL1 as cod1, 
  UTILIZADOR.CODPOSTAL2 as cod2, IMAGEM, N_FUNCIONARIO_SUPER FROM UTILIZADOR JOIN ZONA ON 
(ZONA.CODPOSTAL1 = UTILIZADOR.CODPOSTAL1 AND ZONA.CODPOSTAL2 = UTILIZADOR.CODPOSTAL2) 
WHERE NOME LIKE '%ga%'